# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: appindia
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: serverless2
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless2

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
